---
- name: Setup and configure MySQL
  hosts: memcached
  become: yes

  tasks:
    - name: update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install required packages
      dnf:
        name:
          - epel-release
          - memcached
        state: present

    - name: Enable and start Memcached service
      systemd:
        name: memcached
        enabled: yes
        state: started

    - name: Replace 127.0.0.1 with 0.0.0.0 in memcached config
      replace:
        path: /etc/sysconfig/memcached
        regexp: '127\.0\.0\.1'
        replace: "0.0.0.0"

    - name: Restart Memcached service
      systemd:
        name: memcached
        state: restarted
