---
- name: Setup and configure MySQL
  hosts: mysql
  become: yes
  vars:
    database_pass: "admin123"

  tasks:
    - name: update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install required packages
      dnf:
        name:
          - epel-release
          - git
          - mariadb-server
        state: present

    - name: Enable and start MariaDB service
      systemd:
        name: mariadb
        enabled: yes
        state: started

    - name: Set root password for MySQL
      mysql_user:
        name: root
        password: "{{ database_pass }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        check_implicit_admin: yes
        state: present

    - name: Create database for accounts
      mysql_db:
        name: accounts
        state: present
        login_user: root
        login_password: "{{ database_pass }}"

    - name: Create admin user and grant privileges on accounts database
      mysql_user:
        name: admin
        password: "admin123"
        priv: "accounts.*:ALL"
        host: "{{ item }}"
        state: present
        login_user: root
        login_password: "{{ database_pass }}"

      with_items:
        - "localhost"
        - "%"

    - name: Clone vProfile project repository
      git:
        repo: "https://github.com/hkhcoder/vprofile-project.git"
        dest: "/tmp/vprofile-project"
        version: main

    - name: Restore the database dump
      mysql_db:
        name: accounts
        state: import
        target: "/tmp/vprofile-project/src/main/resources/db_backup.sql"
        login_user: root
        login_password: "{{ database_pass }}"
    - name: Restart MariaDB service
      systemd:
        name: mariadb
        state: restarted
