---
- name: Update package lists
  become: true
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy the Nginx configuration file for vproapp
  copy:
    src: vproapp.conf
    dest: /etc/nginx/sites-available/vproapp
    owner: root
    group: root
    mode: "0644"

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable vproapp Nginx configuration
  file:
    src: /etc/nginx/sites-available/vproapp
    dest: /etc/nginx/sites-enabled/vproapp
    state: link

- name: Start and enable Nginx service
  systemd:
    name: nginx
    enabled: yes
    state: restarted
