---
- name: Setup and configure MySQL
  hosts: reabbitmq
  become: yes

  tasks:
    - name: update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install required packages
      yum:
        name:
          - epel-release
          - wget
        state: present

    - name: Install RabbitMQ repository
      dnf:
        name: centos-release-rabbitmq-38
        state: present

    - name: Install RabbitMQ Server
      dnf:
        name: rabbitmq-server
        enablerepo: centos-rabbitmq-38
        state: present

    - name: Enable and start RabbitMQ Server
      systemd:
        name: rabbitmq-server
        enabled: yes
        state: started

    - name: Allow remote access in RabbitMQ config
      copy:
        content: "[{rabbit, [{loopback_users, []}]}]."
        dest: /etc/rabbitmq/rabbitmq.config

    - name: Add a new RabbitMQ user
      command: rabbitmqctl add_user test test

    - name: Assign administrator tag to the new user
      command: rabbitmqctl set_user_tags test administrator

    - name: Restart RabbitMQ Server to apply any changes
      systemd:
        name: rabbitmq-server
        state: restarted
