---
- name: Update the system
  become: yes
  dnf:
    name: "*"
    state: latest

- name: Install EPEL repository
  dnf:
    name: epel-release
    state: latest

- name: Install Java 11 JDK, development tools, Git, Maven, and Wget
  dnf:
    name:
      - java-11-openjdk
      - java-11-openjdk-devel
      - git
      - maven
      - wget
      - tar
    state: present

- name: Download Apache Tomcat 9.0.75
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.75/bin/apache-tomcat-9.0.75.tar.gz
    dest: /tmp/

- name: Create a Tomcat user
  user:
    name: tomcat
    home: /usr/local/tomcat
    shell: /sbin/nologin

- name: Copy and extract Tomcat files to installation directory
  copy:
    src: /tmp/apache-tomcat-9.0.75/
    dest: /usr/local/tomcat/
    remote_src: yes
    owner: tomcat
    group: tomcat
    mode: "u+rwX,g+rwX,o+rX"

- name: Ensure Tomcat directory ownership
  file:
    path: /usr/local/tomcat/
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Deploy the systemd service file for Tomcat
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd to apply the new Tomcat service configuration
  systemd:
    daemon_reload: yes

- name: Start and enable the Tomcat service to start on boot
  systemd:
    name: tomcat
    enabled: yes
    state: started

- name: Ensure the vprofile project directory is absent
  file:
    path: /tmp/vprofile-project
    state: absent

- name: Create a directory for the vprofile project
  file:
    path: /tmp/vprofile-project
    state: directory
    mode: "0755"

- name: Clone the vprofile project from GitHub
  git:
    repo: https://github.com/hkhcoder/vprofile-project
    dest: /tmp/vprofile-project
    version: main
    clone: yes
    force: yes

- name: Copy application.properties to destination
  copy:
    src: application.properties
    dest: /tmp/vprofile-project/src/main/resources/application.properties
    owner: root
    group: root
    mode: "0644"

- name: Build the project using Maven
  command: mvn install
  args:
    chdir: /tmp/vprofile-project

- name: Stop the Tomcat service before deploying the new application
  systemd:
    name: tomcat
    state: stopped

- name: Wait for 20 seconds to ensure Tomcat has stopped completely
  pause:
    seconds: 20

- name: Remove the default ROOT application from Tomcat's webapps directory
  file:
    path: /usr/local/tomcat/webapps/ROOT
    state: absent

- name: Deploy the new application by copying the WAR file to Tomcat's webapps directory
  copy:
    src: /tmp/vprofile-project/target/vprofile-v2.war
    dest: /usr/local/tomcat/webapps/ROOT.war
    owner: tomcat
    group: tomcat
    remote_src: yes

- name: Start the Tomcat service to deploy the new application
  systemd:
    name: tomcat
    state: started

- name: Wait for 20 seconds to ensure the application is deployed correctly
  pause:
    seconds: 20

- name: Stop and disable the firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Restart the Tomcat service to ensure all changes are applied
  systemd:
    name: tomcat
    state: restarted
