Vagrant.configure("2") do |config|
  # Hostmanager
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.ssh.insert_key = false
  
  ### DB vm ###
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.box_version="9.0.45"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    db01.vm.provision "shell", path: "mysql.sh"
  end
  
  ### Memcache vm ###
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.box_version="9.0.45"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "900"
    end
    mc01.vm.provision "shell", path: "memcache.sh"
  end
  
  ### RabbitMQ vm ###
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.box_version="9.0.45"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.16"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "900"
    end
    rmq01.vm.provision "shell", path: "rabbitmq.sh"
  end
  
  ### Tomcat vm ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    app01.vm.box_version="9.0.45"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    app01.vm.provision "shell", path: "tomcat.sh"
  end
  
  ### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.box_version="20240801.0.0"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
    # web01.vm.network "public_network"
    web01.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "1024"
    end
    web01.vm.provision "shell", path: "nginx.sh"
  end
  
end
