---
nginx_package_name: nginx
nginx_service_name: nginx
nginx_config_file: vproapp
nginx_upstream_server: app01
nginx_upstream_port: 8080
nginx_listen_port: 80

# Default paths for Ubuntu/Debian
nginx_conf_path: "/etc/nginx"
nginx_sites_available: "{{ nginx_conf_path }}/sites-available"
nginx_sites_enabled: "{{ nginx_conf_path }}/sites-enabled"

# Default path for CentOS/RHEL
nginx_conf_d: "{{ nginx_conf_path }}/conf.d"
